# A sample Gemfile
source "https://rubygems.org"

gem 'activerecord', '~> 5.2.0'
#gem 'activerecord', '~> 3.2.0'
#gem 'activerecord', '~> 4.0.0'
#gem 'activerecord', '~> 4.1.0'
#gem 'activerecord', '4.1.2.rc1'

# For testing against Edge Rails
#gem 'activerecord', github: 'rails/rails', branch: 'master'
#gem 'arel', github: 'rails/arel', branch: 'master'

gem 'pg'
gem 'postgresql_cursor', path:"../"
