# A sample Gemfile
source "https://rubygems.org"

#gem 'activerecord', '~> 4.0.0'
gem 'activerecord', '~> 4.1.0'
#gem 'activerecord', '4.1.2.rc1'
#
gem 'pg'
gem 'postgresql_cursor', path:"#{ENV['HOME']}/src/postgresql_cursor"
